export const buttonStyles = [
  "w-full",
  "border-2",
  "focus:ring-4 ",
  "focus:outline-none",
  "focus:border-transparent",
  "text-white",
  "border-white",
  "bg-black",
  "ring-blue-400",
  "transition",
  "ease",
  "duration-300",
  "rounded-lg",
  "py-2",
  "px-4",
  "text-lg",
  "font-bold",
  "hover:border-blue-400",
].join(" ");
